import { 
  ShopSettings, 
  ProductItem, 
  Customer, 
  Invoice, 
  PurchaseOrder, 
  Expense, 
  Supplier,
  StockMovement
} from '../types/solar';

const SETTINGS_KEY = 'solarcraft_settings_v1';
const PRODUCTS_KEY = 'solarcraft_products_v1';
const CUSTOMERS_KEY = 'solarcraft_customers_v1';
const INVOICES_KEY = 'solarcraft_invoices_v1';
const PO_KEY = 'solarcraft_purchase_orders_v1';
const EXPENSES_KEY = 'solarcraft_expenses_v1';
const SUPPLIERS_KEY = 'solarcraft_suppliers_v1';
const STOCK_MOVEMENTS_KEY = 'solarcraft_stock_movements_v1';

export const defaultStockMovements: StockMovement[] = [
  {
    id: 'mov-101',
    productId: 'prod-1',
    productCode: 'SP-585-LONG',
    productName: 'Longi Hi-MO 6 585W Bifacial N-Type TOPCon',
    category: 'SOLAR_PANELS',
    type: 'IN',
    quantity: 62,
    previousStock: 48,
    newStock: 110,
    reason: 'Inbound Container Shipment (Pallet #882)',
    referenceNo: 'PO-2026-001',
    supplierName: 'Apex Tier-1 Photovoltaics Corp',
    unitCost: 115,
    batchOrSerial: 'PALLET-LG-2026-B88',
    scannedBy: 'Warehouse Admin',
    date: '2026-02-18T10:30:00Z',
    notes: '2 Pallets received in pristine condition.',
  },
  {
    id: 'mov-102',
    productId: 'prod-1',
    productCode: 'SP-585-LONG',
    productName: 'Longi Hi-MO 6 585W Bifacial N-Type TOPCon',
    category: 'SOLAR_PANELS',
    type: 'OUT',
    quantity: 18,
    previousStock: 110,
    newStock: 92,
    reason: 'Customer Solar Project Dispatch (10.5kW Rooftop)',
    referenceNo: 'INV-2026-001',
    customerName: 'Col. Farhan Akhtar',
    scannedBy: 'Warehouse Admin',
    date: '2026-02-20T14:15:00Z',
    notes: 'Dispatched for Phase-6 DHA site installation.',
  },
  {
    id: 'mov-103',
    productId: 'prod-4',
    productCode: 'INV-10KW-ON',
    productName: 'Growatt MIN 10000TL-X 10kW Dual MPPT Inverter',
    category: 'INVERTERS',
    type: 'OUT',
    quantity: 1,
    previousStock: 14,
    newStock: 13,
    reason: 'Invoice Order Fulfillment',
    referenceNo: 'INV-2026-001',
    customerName: 'Col. Farhan Akhtar',
    batchOrSerial: 'GW-2026-99281',
    scannedBy: 'Warehouse Admin',
    date: '2026-02-20T14:20:00Z',
    notes: 'Passed initial pre-dispatch bench test.',
  },
  {
    id: 'mov-104',
    productId: 'prod-7',
    productCode: 'BAT-15KWH-FE',
    productName: 'Felicity Solar 15.36kWh LiFePO4 51.2V 300Ah',
    category: 'BATTERIES',
    type: 'IN',
    quantity: 4,
    previousStock: 2,
    newStock: 6,
    reason: 'Supplier Air Freight Restock',
    referenceNo: 'PO-2026-003',
    supplierName: 'InverTech Hybrid Power Systems',
    unitCost: 1950,
    batchOrSerial: 'FEL-300AH-8831..8834',
    scannedBy: 'Warehouse Admin',
    date: '2026-02-22T09:45:00Z',
  }
];

export const defaultSettings: ShopSettings = {
  shopName: 'Helios Solar Solutions & Supply',
  tagline: 'Tier-1 Solar Panels, Hybrid Inverters & Turnkey Installations',
  ownerName: 'Engr. Tariq & Partners',
  phone: '+1 (555) 839-7652',
  email: 'sales@heliossolar.com',
  address: 'Suite 400, Green Energy Commercial Hub, Solar Way',
  city: 'Phoenix, Arizona',
  country: 'United States',
  taxRegistrationNumber: 'AZ-SOLAR-89472-X',
  currency: '$',
  currencyPosition: 'BEFORE',
  defaultTaxRate: 5,
  bankName: 'First Renewable Energy Bank',
  bankAccountTitle: 'Helios Solar Solutions LLC',
  bankAccountNumber: '0988-2948-1102-4451',
  ibanOrSwift: 'FREBUS33PHX',
  invoicePrefix: 'INV-2026-',
  quotationPrefix: 'QT-2026-',
  poPrefix: 'PO-2026-',
  termsAndConditions: '1. 80% Advance payment with order confirmation; balance 20% upon successful testing and commissioning.\n2. Warranty is subject to manufacturer terms; physical or lightning surge damage is excluded.\n3. Quotation valid for 14 days due to solar market price volatility.',
  warrantyDisclaimer: 'Solar Panels: 12-Year Product Warranty & 25-Year Linear Power Output Warranty. Inverter: 5-Year Replacement Warranty. LiFePO4 Batteries: 6,000 Cycles / 10-Year Warranty.',
  logoUrl: '',
  showSignatureStamp: true,
  ownerPin: '7788',
  enableOwnerPin: true,
  partnerName: 'Procurement Partner',
  partnerPin: '1234',
  enablePartnerMode: true,
  customCategories: ['EV_CHARGERS', 'SOLAR_LIGHTS', 'SOLAR_WATER_HEATERS'],
};

export const defaultSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Apex Tier-1 Photovoltaics Corp',
    companyName: 'Apex PV Wholesale Dist.',
    contactPerson: 'David Vance',
    phone: '+1 (555) 304-9988',
    email: 'orders@apexpvdist.com',
    address: '900 Port Industrial Blvd',
    city: 'Los Angeles, CA',
    taxNumber: 'US-CA-992144',
    suppliedCategories: ['SOLAR_PANELS', 'INVERTERS'],
    rating: 5,
    bankDetails: 'Bank of America - Acc # 882947192',
    notes: 'Primary importer for Longi and Canadian Solar pallets.',
    totalPurchased: 48500,
    totalOutstanding: 4500,
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'sup-2',
    name: 'InverTech Hybrid Power Systems',
    companyName: 'InverTech Global Supply',
    contactPerson: 'Michael Chang',
    phone: '+1 (555) 771-4433',
    email: 'sales@invertechglobal.com',
    address: '42 Silicon Avenue, Tech Park',
    city: 'Austin, TX',
    taxNumber: 'US-TX-448102',
    suppliedCategories: ['INVERTERS', 'BATTERIES'],
    rating: 4.8,
    bankDetails: 'Chase Bank - Acc # 339182740',
    notes: 'Authorized distributor for Deye, Growatt, and Pylontech.',
    totalPurchased: 36200,
    totalOutstanding: 0,
    createdAt: '2026-01-15T11:00:00Z',
  },
  {
    id: 'sup-3',
    name: 'SunMount Aluminum & Fasteners Ltd',
    companyName: 'SunMount Industrial Fabrications',
    contactPerson: 'Robert Sterling',
    phone: '+1 (555) 621-8890',
    email: 'sterling@sunmountfab.com',
    address: '14 Industrial Zone North',
    city: 'Phoenix, AZ',
    taxNumber: 'US-AZ-551982',
    suppliedCategories: ['STRUCTURE_MOUNTING', 'ACCESSORIES'],
    rating: 4.9,
    bankDetails: 'Wells Fargo - Acc # 901182341',
    notes: 'Supplies AL6005-T5 extruded anodized solar mounting rails, L-feet, and custom elevated roof structures.',
    totalPurchased: 14800,
    totalOutstanding: 1200,
    createdAt: '2026-01-20T09:30:00Z',
  },
  {
    id: 'sup-4',
    name: 'VoltSafe Electrical & DC Switchgear',
    companyName: 'VoltSafe Components Inc',
    contactPerson: 'Sarah Jenkins',
    phone: '+1 (555) 912-3344',
    email: 'info@voltsafedc.com',
    address: '88 Voltage Highway',
    city: 'Denver, CO',
    taxNumber: 'US-CO-772911',
    suppliedCategories: ['SWITCHGEAR_PROTECTION', 'CABLES_WIRES'],
    rating: 4.7,
    bankDetails: 'US Bank - Acc # 449102834',
    notes: 'Supplies 1000V/1500V DC Breakers, Surge Protectors (SPD), MC4 connectors, and solar double-sheathed copper cables.',
    totalPurchased: 9400,
    totalOutstanding: 0,
    createdAt: '2026-02-01T14:00:00Z',
  },
];

export const defaultProducts: ProductItem[] = [
  {
    id: 'prod-1',
    code: 'SP-LONGI-585',
    name: 'Longi Hi-MO 6 Explorer 585W Bifacial N-Type',
    category: 'SOLAR_PANELS',
    brand: 'Longi Solar',
    model: 'LR5-72HBD-585M',
    specs: '585 Watt, N-Type TOPCon Mono, Dual Glass Bifacial, 22.6% Efficiency, Tier-1',
    unit: 'Pieces',
    costPrice: 88,
    sellingPrice: 125,
    stockQty: 84,
    minStockAlert: 20,
    wattageRating: 585,
    warrantyYears: 25,
    notes: 'Top seller for residential & commercial rooftops. 36 pcs per pallet.',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    id: 'prod-2',
    code: 'SP-CANADIAN-600',
    name: 'Canadian Solar HiKu7 600W Monocrystalline',
    category: 'SOLAR_PANELS',
    brand: 'Canadian Solar',
    model: 'CS7L-600MS',
    specs: '600 Watt, Monocrystalline Half-Cut Cell, 21.4% Efficiency, Heavy Snow/Wind Load',
    unit: 'Pieces',
    costPrice: 92,
    sellingPrice: 132,
    stockQty: 48,
    minStockAlert: 15,
    wattageRating: 600,
    warrantyYears: 25,
    notes: 'High-yield commercial panels.',
    createdAt: '2026-01-12T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'prod-3',
    code: 'SP-JINKO-580',
    name: 'Jinko Tiger Neo N-Type 580W Bifacial',
    category: 'SOLAR_PANELS',
    brand: 'Jinko Solar',
    model: 'JKM580N-72HL4-BDV',
    specs: '580 Watt, N-Type TOPCon Dual-Glass, High Temperature Coefficient',
    unit: 'Pieces',
    costPrice: 86,
    sellingPrice: 122,
    stockQty: 12,
    minStockAlert: 24, // Trigger low stock indicator
    wattageRating: 580,
    warrantyYears: 25,
    notes: 'High demand, order new shipment soon.',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prod-4',
    code: 'INV-DEYE-12K-HYB',
    name: 'Deye 12kW Three-Phase Hybrid Inverter',
    category: 'INVERTERS',
    brand: 'Deye',
    model: 'SUN-12K-SG04LP3-EU',
    specs: '12 kW, 3-Phase 48V/51.2V Low Voltage Hybrid Inverter, Dual MPPT, Smart Load & Generator port',
    unit: 'Units',
    costPrice: 1650,
    sellingPrice: 2250,
    stockQty: 6,
    minStockAlert: 3,
    wattageRating: 12000,
    warrantyYears: 5,
    notes: 'Includes WiFi dongle and smart CT clamps for zero-export.',
    createdAt: '2026-01-18T00:00:00Z',
    updatedAt: '2026-08-19T00:00:00Z',
  },
  {
    id: 'prod-5',
    code: 'INV-GROWATT-10K-ON',
    name: 'Growatt MOD 10KTL3-X 10kW On-Grid Inverter',
    category: 'INVERTERS',
    brand: 'Growatt',
    model: 'MOD 10KTL3-X',
    specs: '10 kW, 3-Phase Grid-Tied Inverter, Dual MPPT, 98.6% Efficiency, OLED Touch Key',
    unit: 'Units',
    costPrice: 920,
    sellingPrice: 1350,
    stockQty: 8,
    minStockAlert: 2,
    wattageRating: 10000,
    warrantyYears: 5,
    notes: 'Standard choice for on-grid 3-phase solar setups.',
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-08-10T00:00:00Z',
  },
  {
    id: 'prod-6',
    code: 'INV-HUAWEI-20K',
    name: 'Huawei SUN2000-20KTL-M2 20kW Commercial Inverter',
    category: 'INVERTERS',
    brand: 'Huawei',
    model: 'SUN2000-20KTL-M2',
    specs: '20 kW, 3-Phase Smart PV Controller, 4 MPPT Inputs, AI-Powered AFCI protection',
    unit: 'Units',
    costPrice: 1850,
    sellingPrice: 2600,
    stockQty: 3,
    minStockAlert: 2,
    wattageRating: 20000,
    warrantyYears: 5,
    notes: 'For industrial and large commercial installations.',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-08-12T00:00:00Z',
  },
  {
    id: 'prod-7',
    code: 'BAT-PYLON-US5000',
    name: 'Pylontech US5000 4.8kWh LiFePO4 Battery',
    category: 'BATTERIES',
    brand: 'Pylontech',
    model: 'US5000 48V 100Ah',
    specs: '4.8 kWh, 48V Lithium Iron Phosphate (LiFePO4), 95% DoD, 6000+ Cycles, Modular Rack Mount',
    unit: 'Units',
    costPrice: 1100,
    sellingPrice: 1550,
    stockQty: 10,
    minStockAlert: 4,
    capacityKwh: 4.8,
    warrantyYears: 10,
    notes: 'Plug-and-play communication with Deye and Growatt inverters.',
    createdAt: '2026-02-05T00:00:00Z',
    updatedAt: '2026-08-17T00:00:00Z',
  },
  {
    id: 'prod-8',
    code: 'BAT-DYNESS-5KW',
    name: 'Dyness BX51100 5.12kWh LiFePO4 Energy Box',
    category: 'BATTERIES',
    brand: 'Dyness',
    model: 'BX51100 51.2V 100Ah',
    specs: '5.12 kWh, 51.2V 100Ah LiFePO4 Battery, Built-in Smart BMS with CAN/RS485',
    unit: 'Units',
    costPrice: 1180,
    sellingPrice: 1680,
    stockQty: 7,
    minStockAlert: 3,
    capacityKwh: 5.12,
    warrantyYears: 10,
    notes: 'Expandable up to 40 units in parallel.',
    createdAt: '2026-02-08T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'prod-9',
    code: 'STR-ELEVATED-L3',
    name: 'Elevated Rooftop GI/Aluminum Customized Structure (per kW)',
    category: 'STRUCTURE_MOUNTING',
    brand: 'SunMount Custom',
    model: 'L3 Heavy Elevated Truss',
    specs: 'Hot-Dip Galvanized / Anodized Aluminum 6005-T5, Elevated 6-8ft walkway frame, 120mph wind resistance',
    unit: 'kW Structure',
    costPrice: 38,
    sellingPrice: 65,
    stockQty: 95,
    minStockAlert: 20,
    warrantyYears: 10,
    notes: 'Fabricated for rooftop spaces to allow rooftop recreation underneath.',
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-08-20T00:00:00Z',
  },
  {
    id: 'prod-10',
    code: 'CAB-SOLAR-6MM',
    name: '6mm² Double Insulated Solar DC Cable (100m Roll)',
    category: 'CABLES_WIRES',
    brand: 'KBE / Helukabel',
    model: 'PV1-F 6.0mm² Red/Black',
    specs: 'TUV Certified, 1500V DC rated, Halogen-free, UV and ozone resistant, 100m roll',
    unit: 'Rolls',
    costPrice: 65,
    sellingPrice: 98,
    stockQty: 18,
    minStockAlert: 5,
    warrantyYears: 25,
    notes: 'Premium pure tinned electrolytic copper.',
    createdAt: '2026-01-22T00:00:00Z',
    updatedAt: '2026-08-15T00:00:00Z',
  },
  {
    id: 'prod-11',
    code: 'SW-DC-DIST-BOX',
    name: 'Complete DC/AC Distribution Box (10kW Setup)',
    category: 'SWITCHGEAR_PROTECTION',
    brand: 'Schneider / Suntree',
    model: 'DB-10KW-PRO',
    specs: 'IP65 Waterproof DB with 2x 1000V DC Breakers, 2x DC SPD, AC 4P Breaker, AC SPD, Voltage Protector',
    unit: 'Sets',
    costPrice: 95,
    sellingPrice: 160,
    stockQty: 14,
    minStockAlert: 4,
    warrantyYears: 3,
    notes: 'Pre-wired ready for rapid on-site installation.',
    createdAt: '2026-01-25T00:00:00Z',
    updatedAt: '2026-08-14T00:00:00Z',
  },
  {
    id: 'prod-12',
    code: 'SRV-INSTALL-LABOR',
    name: 'Turnkey Solar Installation, Earthing & Commissioning (per kW)',
    category: 'SERVICES_LABOR',
    brand: 'Helios In-House Crew',
    model: 'Turnkey Standard',
    specs: 'Panel mounting, DC/AC cable dressing, Dual copper earthing chemical pits (<3 ohms), Testing & Commissioning',
    unit: 'kW',
    costPrice: 25,
    sellingPrice: 45,
    stockQty: 999,
    minStockAlert: 10,
    warrantyYears: 1,
    notes: '1-year free workmanship maintenance.',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
  {
    id: 'prod-13',
    code: 'SRV-COMMISSIONING',
    name: 'Comprehensive Solar Testing, Earthing & Commissioning Service',
    category: 'SERVICES_LABOR',
    brand: 'Helios Field Ops',
    model: 'Commissioning Pack',
    specs: 'Megger insulation test, AC/DC circuit verification, Earth resistance pit testing (<5 Ohm) & load sync',
    unit: 'Job',
    costPrice: 280,
    sellingPrice: 450,
    stockQty: 999,
    minStockAlert: 1,
    warrantyYears: 1,
    notes: 'Complete testing protocol and certification before system energization.',
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
  },
];

export const defaultCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Dr. Arthur Mitchell',
    customerType: 'RESIDENTIAL',
    phone: '+1 (555) 234-8891',
    whatsapp: '+1 (555) 234-8891',
    email: 'arthur.mitchell@gmail.com',
    address: '742 Evergreen Terrace, North Heights',
    city: 'Phoenix, AZ',
    nationalIdOrTax: 'SSN-***-9921',
    sanctionedLoadKw: 15,
    utilityDiscom: 'Arizona Public Power (APS)',
    consumerNumber: 'REF-8839-201',
    installedCapacityKw: 11.7,
    systemType: 'HYBRID',
    inverterSerial: 'DEYE-2026-9938102',
    panelBrandModel: 'Longi 585W Bifacial x 20 Panels',
    installationDate: '2026-07-15',
    warrantyExpiryDate: '2031-07-15',
    totalInvoiced: 7850,
    totalPaid: 7850,
    balanceDue: 0,
    notes: 'Client runs 2x 2-Ton Inverter ACs. Hybrid system with 1x Pylontech 4.8kWh battery.',
    createdAt: '2026-06-20T10:00:00Z',
    updatedAt: '2026-07-18T12:00:00Z',
  },
  {
    id: 'cust-2',
    name: 'Sonora Cold Storage & Logistics Ltd',
    customerType: 'COMMERCIAL',
    phone: '+1 (555) 890-4422',
    whatsapp: '+1 (555) 890-4422',
    email: 'operations@sonoracold.com',
    address: 'Plot 45-B, Industrial Estate 3',
    city: 'Tucson, AZ',
    nationalIdOrTax: 'TAX-AZ-9981240',
    sanctionedLoadKw: 50,
    utilityDiscom: 'Tucson Electric Power (TEP)',
    consumerNumber: 'REF-7712-409',
    installedCapacityKw: 35.1,
    systemType: 'ON_GRID',
    inverterSerial: 'HUAWEI-SUN-2026-44810',
    panelBrandModel: 'Canadian Solar 600W x 60 Panels',
    installationDate: '2026-08-02',
    warrantyExpiryDate: '2031-08-02',
    totalInvoiced: 21500,
    totalPaid: 15000,
    balanceDue: 6500,
    notes: 'Commercial rooftop system. Final milestone payment due after 30 days grid export validation.',
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-08-05T14:30:00Z',
  },
  {
    id: 'cust-3',
    name: 'Harrison Green Organic Farms',
    customerType: 'AGRICULTURAL',
    phone: '+1 (555) 443-1120',
    whatsapp: '+1 (555) 443-1120',
    email: 'harrisonfarms@agrinet.org',
    address: 'Mile 18, Valley Rural Road',
    city: 'Casa Grande, AZ',
    nationalIdOrTax: 'TAX-AZ-331088',
    sanctionedLoadKw: 25,
    utilityDiscom: 'Rural Agri Power Coop',
    consumerNumber: 'AGRI-6629-11',
    installedCapacityKw: 17.5,
    systemType: 'SOLAR_PUMP',
    inverterSerial: 'PUMP-INV-2026-8812',
    panelBrandModel: 'Jinko 580W x 30 Panels',
    installationDate: '2026-08-10',
    warrantyExpiryDate: '2031-08-10',
    totalInvoiced: 11400,
    totalPaid: 11400,
    balanceDue: 0,
    notes: '15 HP Solar submersible water pump with VFD drive.',
    createdAt: '2026-07-15T11:00:00Z',
    updatedAt: '2026-08-12T16:00:00Z',
  },
  {
    id: 'cust-4',
    name: 'Elena Rostova (Villa 14)',
    customerType: 'RESIDENTIAL',
    phone: '+1 (555) 782-9011',
    email: 'elena.rostova@outlook.com',
    address: '14 Whispering Palms Drive',
    city: 'Scottsdale, AZ',
    sanctionedLoadKw: 10,
    utilityDiscom: 'APS',
    consumerNumber: 'REF-3341-99',
    installedCapacityKw: 7.02,
    systemType: 'ON_GRID',
    inverterSerial: 'GROW-10K-99881',
    panelBrandModel: 'Longi 585W x 12 Panels',
    totalInvoiced: 0,
    totalPaid: 0,
    balanceDue: 0,
    notes: 'Installation in progress. Structure mounted, panels delivered.',
    createdAt: '2026-08-14T08:30:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
];

export const defaultInvoices: Invoice[] = [
  {
    id: 'inv-1',
    invoiceNumber: 'INV-2026-001',
    type: 'INVOICE',
    customerId: 'cust-1',
    customerName: 'Dr. Arthur Mitchell',
    customerPhone: '+1 (555) 234-8891',
    customerEmail: 'arthur.mitchell@gmail.com',
    customerAddress: '742 Evergreen Terrace, North Heights',
    customerCity: 'Phoenix, AZ',
    projectSystemCapacityKw: 11.7,
    systemType: 'HYBRID',
    installationAddress: '742 Evergreen Terrace, North Heights, Phoenix, AZ',
    date: '2026-07-10',
    dueDate: '2026-07-20',
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        description: 'Longi Hi-MO 6 585W Bifacial N-Type Solar Panels',
        category: 'SOLAR_PANELS',
        brand: 'Longi Solar',
        specs: '585W Tier-1 Dual Glass N-Type TOPCon',
        serialNumbers: 'LR5-72HBD-2026-001 through 020 (20 Pcs)',
        warrantyPeriod: '12 Years Product / 25 Years Performance',
        quantity: 20,
        unit: 'Pieces',
        unitPrice: 125,
        costPrice: 88,
        discountPercent: 0,
        total: 2500,
      },
      {
        id: 'item-2',
        productId: 'prod-4',
        description: 'Deye 12kW Three-Phase Hybrid Inverter',
        category: 'INVERTERS',
        brand: 'Deye',
        specs: '12kW 3-Phase Low Voltage 48V with WiFi Monitoring',
        serialNumbers: 'DEYE-2026-9938102',
        warrantyPeriod: '5 Years Replacement Warranty',
        quantity: 1,
        unit: 'Units',
        unitPrice: 2250,
        costPrice: 1650,
        discountPercent: 0,
        total: 2250,
      },
      {
        id: 'item-3',
        productId: 'prod-7',
        description: 'Pylontech US5000 4.8kWh LiFePO4 Battery Module',
        category: 'BATTERIES',
        brand: 'Pylontech',
        specs: '4.8kWh 48V 100Ah 6,000 Cycles 95% DoD',
        serialNumbers: 'PYL-US5000-881920',
        warrantyPeriod: '10 Years / 6,000 Cycles Warranty',
        quantity: 1,
        unit: 'Units',
        unitPrice: 1550,
        costPrice: 1100,
        discountPercent: 0,
        total: 1550,
      },
      {
        id: 'item-4',
        productId: 'prod-9',
        description: 'Elevated Rooftop GI/Aluminum Customized Structure',
        category: 'STRUCTURE_MOUNTING',
        brand: 'SunMount Custom',
        specs: 'Custom L3 elevated walkway frame for 11.7kW array',
        warrantyPeriod: '10 Years Fabrication Warranty',
        quantity: 11.7,
        unit: 'kW Structure',
        unitPrice: 65,
        costPrice: 38,
        discountPercent: 0,
        total: 760.5,
      },
      {
        id: 'item-5',
        productId: 'prod-11',
        description: 'Complete DC/AC Distribution Box with Surge Protectors',
        category: 'SWITCHGEAR_PROTECTION',
        brand: 'Schneider / Suntree',
        specs: 'Dual string DC DB + 3-Phase AC DB with SPDs',
        warrantyPeriod: '3 Years Warranty',
        quantity: 1,
        unit: 'Sets',
        unitPrice: 160,
        costPrice: 95,
        discountPercent: 0,
        total: 160,
      },
      {
        id: 'item-6',
        productId: 'prod-12',
        description: 'Turnkey Installation, Chemical Earthing & Testing',
        category: 'SERVICES_LABOR',
        brand: 'Helios Crew',
        specs: 'Wiring, earthing pit resistance < 2.5 ohms, commissioning',
        warrantyPeriod: '1 Year Free Service',
        quantity: 11.7,
        unit: 'kW',
        unitPrice: 45,
        costPrice: 25,
        discountPercent: 0,
        total: 526.5,
      },
      {
        id: 'item-7',
        productId: 'prod-13',
        description: 'Comprehensive Solar Testing, Earthing & Commissioning Service',
        category: 'SERVICES_LABOR',
        brand: 'Helios Field Ops',
        specs: 'Megger insulation test, earth pit resistance testing & commissioning certificate',
        warrantyPeriod: '1 Year',
        quantity: 1,
        unit: 'Job',
        unitPrice: 450,
        costPrice: 280,
        discountPercent: 0,
        total: 450,
      },
    ],
    subtotal: 8197,
    discountTotal: 347,
    taxPercent: 0, // Solar tax exemption
    taxAmount: 0,
    shippingOrFreight: 0,
    installationCharge: 0,
    grandTotal: 7850,
    paidAmount: 7850,
    balanceDue: 0,
    status: 'PAID',
    payments: [
      {
        id: 'pay-1',
        date: '2026-07-10',
        amount: 5000,
        method: 'BANK_TRANSFER',
        referenceNo: 'FT-APS-882910',
        notes: 'Initial booking & hardware order deposit (64%)',
      },
      {
        id: 'pay-2',
        date: '2026-07-18',
        amount: 2850,
        method: 'ONLINE',
        referenceNo: 'TX-ONLINE-9921',
        notes: 'Final balance after system power-on and APS meter sync',
      },
    ],
    termsAndConditions: 'All solar panels covered by 25-year performance warranty. Inverter covered by 5-year replacement warranty. Customer provided with user manual and smartphone monitoring app login.',
    warrantyNotes: 'Panels: 25 Yrs, Inverter: 5 Yrs, Battery: 10 Yrs',
    notes: 'Customer very pleased with generation output (averaging 55 kWh/day in July).',
    createdAt: '2026-07-10T10:00:00Z',
    updatedAt: '2026-07-18T12:00:00Z',
  },
  {
    id: 'inv-2',
    invoiceNumber: 'INV-2026-002',
    type: 'INVOICE',
    customerId: 'cust-2',
    customerName: 'Sonora Cold Storage & Logistics Ltd',
    customerPhone: '+1 (555) 890-4422',
    customerEmail: 'operations@sonoracold.com',
    customerAddress: 'Plot 45-B, Industrial Estate 3',
    customerCity: 'Tucson, AZ',
    projectSystemCapacityKw: 35.1,
    systemType: 'ON_GRID',
    installationAddress: 'Plot 45-B, Industrial Estate 3, Tucson, AZ',
    date: '2026-08-01',
    dueDate: '2026-08-30',
    items: [
      {
        id: 'item-201',
        productId: 'prod-2',
        description: 'Canadian Solar HiKu7 600W Monocrystalline Panels',
        category: 'SOLAR_PANELS',
        brand: 'Canadian Solar',
        specs: '600W Tier-1 Mono Half-Cell Module',
        serialNumbers: 'CS7L-2026-00101 to 00160 (60 Panels)',
        warrantyPeriod: '25 Years Linear Performance Warranty',
        quantity: 60,
        unit: 'Pieces',
        unitPrice: 130,
        costPrice: 92,
        discountPercent: 0,
        total: 7800,
      },
      {
        id: 'item-202',
        productId: 'prod-6',
        description: 'Huawei SUN2000-20KTL-M2 20kW Commercial Inverters',
        category: 'INVERTERS',
        brand: 'Huawei',
        specs: '20kW 3-Phase Smart Grid Inverters (2x Units for 35kW+)',
        serialNumbers: 'HUAWEI-SUN-2026-44810, HUAWEI-SUN-2026-44811',
        warrantyPeriod: '5 Years Manufacturer Warranty',
        quantity: 2,
        unit: 'Units',
        unitPrice: 2550,
        costPrice: 1850,
        discountPercent: 0,
        total: 5100,
      },
      {
        id: 'item-203',
        productId: 'prod-9',
        description: 'Commercial Rooftop Tin-Roof Railing & Clamping Structure',
        category: 'STRUCTURE_MOUNTING',
        brand: 'SunMount Custom',
        specs: 'Anodized AL6005-T5 Rails with EPDM waterproof rubber clamps for metal sheet roof',
        warrantyPeriod: '10 Years Warranty',
        quantity: 36,
        unit: 'kW Structure',
        unitPrice: 55,
        costPrice: 35,
        discountPercent: 0,
        total: 1980,
      },
      {
        id: 'item-204',
        productId: 'prod-10',
        description: '6mm² Double Insulated Solar DC Cable (100m Roll)',
        category: 'CABLES_WIRES',
        brand: 'KBE / Helukabel',
        specs: 'TUV Certified Pure Tinned Copper DC Wire',
        warrantyPeriod: '25 Years',
        quantity: 6,
        unit: 'Rolls',
        unitPrice: 98,
        costPrice: 65,
        discountPercent: 0,
        total: 588,
      },
      {
        id: 'item-205',
        productId: 'prod-12',
        description: 'Industrial Installation, 4-Point Earthing Grid & Testing',
        category: 'SERVICES_LABOR',
        brand: 'Helios Industrial Crew',
        specs: 'Heavy duty earthing, AC sync panel, civil load distribution',
        warrantyPeriod: '1 Year Warranty',
        quantity: 36,
        unit: 'kW',
        unitPrice: 42,
        costPrice: 24,
        discountPercent: 0,
        total: 1512,
      },
      {
        id: 'item-206',
        productId: 'prod-13',
        description: 'Commercial Testing, Earthing Certification & Energization',
        category: 'SERVICES_LABOR',
        brand: 'Helios Field Ops',
        specs: '3-Phase electrical safety audit, earth grounding report & grid sync',
        warrantyPeriod: '1 Year',
        quantity: 1,
        unit: 'Job',
        unitPrice: 650,
        costPrice: 400,
        discountPercent: 0,
        total: 650,
      },
    ],
    subtotal: 17630,
    discountTotal: 0,
    taxPercent: 0,
    taxAmount: 0,
    shippingOrFreight: 370,
    installationCharge: 3500,
    grandTotal: 21500,
    paidAmount: 15000,
    balanceDue: 6500,
    status: 'PARTIAL',
    payments: [
      {
        id: 'pay-201',
        date: '2026-08-01',
        amount: 15000,
        method: 'CHEQUE',
        referenceNo: 'CHQ-CORP-09941',
        notes: 'Stage 1 Advance payment for hardware procurement',
      },
    ],
    termsAndConditions: 'Milestone 1 (70% Paid): Prior to delivery. Milestone 2 (30% Due): 30 days after commercial commissioning.',
    warrantyNotes: 'Panels: 25 Yrs, Inverters: 5 Yrs, Workmanship: 1 Yr',
    notes: 'Expected monthly generation ~ 5,400 kWh, saving client ~$1,350/month in utility bills.',
    createdAt: '2026-08-01T08:00:00Z',
    updatedAt: '2026-08-05T14:30:00Z',
  },
  {
    id: 'inv-3',
    invoiceNumber: 'QT-2026-003',
    type: 'QUOTATION',
    customerId: 'cust-4',
    customerName: 'Elena Rostova (Villa 14)',
    customerPhone: '+1 (555) 782-9011',
    customerEmail: 'elena.rostova@outlook.com',
    customerAddress: '14 Whispering Palms Drive',
    customerCity: 'Scottsdale, AZ',
    projectSystemCapacityKw: 7.02,
    systemType: 'ON_GRID',
    installationAddress: '14 Whispering Palms Drive, Scottsdale, AZ',
    date: '2026-08-14',
    dueDate: '2026-08-28',
    items: [
      {
        id: 'item-301',
        productId: 'prod-1',
        description: 'Longi Hi-MO 6 585W Bifacial N-Type Solar Panels',
        category: 'SOLAR_PANELS',
        brand: 'Longi Solar',
        specs: '585W TOPCon Bifacial Mono',
        warrantyPeriod: '25 Years Linear Performance Warranty',
        quantity: 12,
        unit: 'Pieces',
        unitPrice: 125,
        costPrice: 88,
        discountPercent: 0,
        total: 1500,
      },
      {
        id: 'item-302',
        productId: 'prod-5',
        description: 'Growatt MOD 10KTL3-X 10kW On-Grid Inverter',
        category: 'INVERTERS',
        brand: 'Growatt',
        specs: '10kW 3-Phase Grid-Tied Inverter with ShineWiFi Dongle',
        warrantyPeriod: '5 Years Warranty',
        quantity: 1,
        unit: 'Units',
        unitPrice: 1350,
        costPrice: 920,
        discountPercent: 0,
        total: 1350,
      },
      {
        id: 'item-303',
        productId: 'prod-9',
        description: 'Elevated Rooftop GI/Aluminum Customized Structure',
        category: 'STRUCTURE_MOUNTING',
        brand: 'SunMount Custom',
        specs: 'Custom 7kW elevated rooftop frame',
        warrantyPeriod: '10 Years Warranty',
        quantity: 7,
        unit: 'kW Structure',
        unitPrice: 65,
        costPrice: 38,
        discountPercent: 0,
        total: 455,
      },
      {
        id: 'item-304',
        productId: 'prod-11',
        description: 'Complete DC/AC Distribution Box with Surge Protectors',
        category: 'SWITCHGEAR_PROTECTION',
        brand: 'Schneider / Suntree',
        specs: 'IP65 DB with DC & AC SPDs and breakers',
        warrantyPeriod: '3 Years Warranty',
        quantity: 1,
        unit: 'Sets',
        unitPrice: 160,
        costPrice: 95,
        discountPercent: 0,
        total: 160,
      },
      {
        id: 'item-305',
        productId: 'prod-12',
        description: 'Turnkey Installation, Earthing Pits & Commissioning',
        category: 'SERVICES_LABOR',
        brand: 'Helios Crew',
        specs: 'Complete wiring, mounting & testing',
        warrantyPeriod: '1 Year Free Service',
        quantity: 7,
        unit: 'kW',
        unitPrice: 45,
        costPrice: 25,
        discountPercent: 0,
        total: 315,
      },
      {
        id: 'item-306',
        productId: 'prod-13',
        description: 'Comprehensive Testing & System Commissioning Package',
        category: 'SERVICES_LABOR',
        brand: 'Helios Field Ops',
        specs: 'Electrical safety testing, string Voc/Isc checks & handover report',
        warrantyPeriod: '1 Year',
        quantity: 1,
        unit: 'Job',
        unitPrice: 450,
        costPrice: 280,
        discountPercent: 0,
        total: 450,
      },
    ],
    subtotal: 4230,
    discountTotal: 0,
    taxPercent: 0,
    taxAmount: 0,
    shippingOrFreight: 0,
    installationCharge: 720,
    grandTotal: 4950,
    paidAmount: 0,
    balanceDue: 0,
    status: 'UNPAID',
    payments: [],
    termsAndConditions: 'Quotation valid for 14 days. Installation scheduled within 3 business days of site inspection.',
    warrantyNotes: 'Panels: 25 Yrs, Inverter: 5 Yrs, Workmanship: 1 Yr',
    notes: 'Quotation converted to active project.',
    createdAt: '2026-08-14T08:30:00Z',
    updatedAt: '2026-08-20T10:00:00Z',
  },
];

export const defaultPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-1',
    poNumber: 'PO-2026-001',
    supplierId: 'sup-1',
    supplierName: 'Apex Tier-1 Photovoltaics Corp',
    supplierPhone: '+1 (555) 304-9988',
    supplierEmail: 'orders@apexpvdist.com',
    supplierAddress: '900 Port Industrial Blvd, Los Angeles, CA',
    orderDate: '2026-07-02',
    expectedDate: '2026-07-08',
    receivedDate: '2026-07-07',
    status: 'RECEIVED',
    items: [
      {
        id: 'po-item-1',
        productId: 'prod-1',
        name: 'Longi Hi-MO 6 585W Bifacial Solar Panels',
        category: 'SOLAR_PANELS',
        brand: 'Longi Solar',
        specs: '585W TOPCon Bifacial Tier-1 (3x Pallets = 108 Pcs)',
        quantity: 108,
        unit: 'Pieces',
        unitCost: 88,
        total: 9504,
        receivedQty: 108,
      },
      {
        id: 'po-item-2',
        productId: 'prod-2',
        name: 'Canadian Solar HiKu7 600W Monocrystalline Panels',
        category: 'SOLAR_PANELS',
        brand: 'Canadian Solar',
        specs: '600W Mono Perc Half-Cell (2x Pallets = 72 Pcs)',
        quantity: 72,
        unit: 'Pieces',
        unitCost: 92,
        total: 6624,
        receivedQty: 72,
      },
    ],
    subtotal: 16128,
    taxAmount: 0,
    shippingFreight: 650,
    grandTotal: 16778,
    paidAmount: 16778,
    balanceDue: 0,
    paymentStatus: 'PAID',
    payments: [
      {
        id: 'po-pay-1',
        date: '2026-07-02',
        amount: 16778,
        method: 'BANK_TRANSFER',
        referenceNo: 'WIRE-APEX-9921',
        notes: 'Full payment wire for 5 container pallets',
      },
    ],
    trackingNo: 'FRT-LA-AZ-88192',
    notes: 'Received in pristine condition at warehouse. All flash test reports verified.',
    createdAt: '2026-07-02T10:00:00Z',
    updatedAt: '2026-07-07T16:00:00Z',
  },
  {
    id: 'po-2',
    poNumber: 'PO-2026-002',
    supplierId: 'sup-2',
    supplierName: 'InverTech Hybrid Power Systems',
    supplierPhone: '+1 (555) 771-4433',
    supplierEmail: 'sales@invertechglobal.com',
    supplierAddress: '42 Silicon Avenue, Tech Park, Austin, TX',
    orderDate: '2026-07-15',
    expectedDate: '2026-07-22',
    receivedDate: '2026-07-21',
    status: 'RECEIVED',
    items: [
      {
        id: 'po-item-201',
        productId: 'prod-4',
        name: 'Deye 12kW Three-Phase Hybrid Inverter',
        category: 'INVERTERS',
        brand: 'Deye',
        specs: '12kW 3-Phase Low Voltage Hybrid',
        quantity: 8,
        unit: 'Units',
        unitCost: 1650,
        total: 13200,
        receivedQty: 8,
      },
      {
        id: 'po-item-202',
        productId: 'prod-7',
        name: 'Pylontech US5000 4.8kWh LiFePO4 Battery',
        category: 'BATTERIES',
        brand: 'Pylontech',
        specs: '4.8kWh 48V 100Ah Modular Battery',
        quantity: 12,
        unit: 'Units',
        unitCost: 1100,
        total: 13200,
        receivedQty: 12,
      },
    ],
    subtotal: 26400,
    taxAmount: 0,
    shippingFreight: 800,
    grandTotal: 27200,
    paidAmount: 27200,
    balanceDue: 0,
    paymentStatus: 'PAID',
    payments: [
      {
        id: 'po-pay-201',
        date: '2026-07-15',
        amount: 27200,
        method: 'BANK_TRANSFER',
        referenceNo: 'WIRE-INV-4412',
        notes: 'Inverters & Lithium batteries batch order',
      },
    ],
    trackingNo: 'TX-EXP-992144',
    notes: 'Delivered directly to central solar showroom.',
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-07-21T15:00:00Z',
  },
  {
    id: 'po-3',
    poNumber: 'PO-2026-003',
    supplierId: 'sup-3',
    supplierName: 'SunMount Aluminum & Fasteners Ltd',
    supplierPhone: '+1 (555) 621-8890',
    supplierEmail: 'sterling@sunmountfab.com',
    supplierAddress: '14 Industrial Zone North, Phoenix, AZ',
    orderDate: '2026-08-18',
    expectedDate: '2026-08-25',
    status: 'ORDERED',
    items: [
      {
        id: 'po-item-301',
        productId: 'prod-9',
        name: 'Elevated Rooftop GI/Aluminum Customized Structure',
        category: 'STRUCTURE_MOUNTING',
        brand: 'SunMount Custom',
        specs: 'AL6005-T5 Extruded Rails & Elevated Leg sets (50 kW capacity)',
        quantity: 50,
        unit: 'kW Structure',
        unitCost: 38,
        total: 1900,
        receivedQty: 0,
      },
    ],
    subtotal: 1900,
    taxAmount: 95,
    shippingFreight: 120,
    grandTotal: 2115,
    paidAmount: 1000,
    balanceDue: 1115,
    paymentStatus: 'PARTIAL',
    payments: [
      {
        id: 'po-pay-301',
        date: '2026-08-18',
        amount: 1000,
        method: 'BANK_TRANSFER',
        referenceNo: 'ADV-SM-009',
        notes: '50% fabrication advance deposit',
      },
    ],
    notes: 'For upcoming residential & commercial installations in September.',
    createdAt: '2026-08-18T11:00:00Z',
    updatedAt: '2026-08-18T11:00:00Z',
  },
];

export const defaultExpenses: Expense[] = [
  {
    id: 'exp-1',
    date: '2026-08-01',
    category: 'SHOP_RENT',
    title: 'Showroom & Solar Warehouse Monthly Rent (August)',
    amount: 2200,
    paymentMethod: 'BANK_TRANSFER',
    payee: 'Sunbelt Commercial Properties Inc',
    referenceNo: 'RENT-AUG-2026',
    taxDeductible: true,
    notes: 'Main shop and backyard equipment staging yard rent.',
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'exp-2',
    date: '2026-08-05',
    category: 'TECHNICIAN_LABOR',
    title: 'Lead Solar Installers & Electricians Bi-Weekly Wages',
    amount: 1850,
    paymentMethod: 'BANK_TRANSFER',
    payee: 'Installation Team (Crew A & B - 4 Techs)',
    referenceNo: 'PAYROLL-AUG-01',
    taxDeductible: true,
    notes: 'Paid for Sonora Cold Storage & Mitchell residential jobs.',
    createdAt: '2026-08-05T17:00:00Z',
  },
  {
    id: 'exp-3',
    date: '2026-08-08',
    category: 'TRANSPORT_FREIGHT',
    title: 'Crane & Hydraulic Lift Rental for Commercial Rooftop Panel Lifting',
    amount: 450,
    paymentMethod: 'CASH',
    payee: 'Valley Crane Services LLC',
    referenceNo: 'CRANE-8819',
    taxDeductible: true,
    relatedCustomerId: 'cust-2',
    relatedCustomerName: 'Sonora Cold Storage & Logistics Ltd',
    notes: 'Lifted 60x 600W panels to 3-story industrial roof safely.',
    createdAt: '2026-08-08T14:00:00Z',
  },
  {
    id: 'exp-4',
    date: '2026-08-12',
    category: 'TOOLS_EQUIPMENT',
    title: 'Solar Earth Grounding Resistance Tester & MC4 Crimping Tool Sets',
    amount: 320,
    paymentMethod: 'CREDIT_CARD',
    payee: 'Fluke / Klein Tools Direct',
    referenceNo: 'CC-TOOL-4491',
    taxDeductible: true,
    notes: 'Earth resistance digital tester (<3 ohm verification requirement).',
    createdAt: '2026-08-12T11:30:00Z',
  },
  {
    id: 'exp-5',
    date: '2026-08-15',
    category: 'MARKETING_ADS',
    title: 'Local Google & Facebook Ads for Residential Solar Sizing Slogans',
    amount: 280,
    paymentMethod: 'CREDIT_CARD',
    payee: 'Google Ads & Meta Ads',
    referenceNo: 'ADS-AUG-15',
    taxDeductible: true,
    notes: 'Targeting homeowners with high summer electricity bills.',
    createdAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'exp-6',
    date: '2026-08-17',
    category: 'UTILITIES_ELECTRICITY',
    title: 'Shop Electricity & High-Speed Internet Bill',
    amount: 195,
    paymentMethod: 'ONLINE',
    payee: 'Arizona Public Service / Cox Business',
    referenceNo: 'UTIL-AUG-88',
    taxDeductible: true,
    notes: 'Office utilities.',
    createdAt: '2026-08-17T16:00:00Z',
  },
];

// Storage Helper functions
export const loadShopSettings = (): ShopSettings => {
  try {
    const data = localStorage.getItem(SETTINGS_KEY);
    if (!data) return defaultSettings;
    const parsed = JSON.parse(data);
    if (!parsed || typeof parsed !== 'object') return defaultSettings;
    return {
      ...defaultSettings,
      ...parsed,
      customCategories: Array.isArray(parsed.customCategories)
        ? parsed.customCategories.filter((c: any) => typeof c === 'string' && c.trim())
        : defaultSettings.customCategories,
    };
  } catch {
    return defaultSettings;
  }
};

export const saveShopSettings = (settings: ShopSettings): void => {
  localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings));
};

export const loadProducts = (): ProductItem[] => {
  try {
    const data = localStorage.getItem(PRODUCTS_KEY);
    return data ? JSON.parse(data) : defaultProducts;
  } catch {
    return defaultProducts;
  }
};

export const saveProducts = (products: ProductItem[]): void => {
  localStorage.setItem(PRODUCTS_KEY, JSON.stringify(products));
};

export const loadCustomers = (): Customer[] => {
  try {
    const data = localStorage.getItem(CUSTOMERS_KEY);
    return data ? JSON.parse(data) : defaultCustomers;
  } catch {
    return defaultCustomers;
  }
};

export const saveCustomers = (customers: Customer[]): void => {
  localStorage.setItem(CUSTOMERS_KEY, JSON.stringify(customers));
};

export const loadInvoices = (): Invoice[] => {
  try {
    const data = localStorage.getItem(INVOICES_KEY);
    return data ? JSON.parse(data) : defaultInvoices;
  } catch {
    return defaultInvoices;
  }
};

export const saveInvoices = (invoices: Invoice[]): void => {
  localStorage.setItem(INVOICES_KEY, JSON.stringify(invoices));
};

export const loadPurchaseOrders = (): PurchaseOrder[] => {
  try {
    const data = localStorage.getItem(PO_KEY);
    return data ? JSON.parse(data) : defaultPurchaseOrders;
  } catch {
    return defaultPurchaseOrders;
  }
};

export const savePurchaseOrders = (orders: PurchaseOrder[]): void => {
  localStorage.setItem(PO_KEY, JSON.stringify(orders));
};

export const loadExpenses = (): Expense[] => {
  try {
    const data = localStorage.getItem(EXPENSES_KEY);
    return data ? JSON.parse(data) : defaultExpenses;
  } catch {
    return defaultExpenses;
  }
};

export const saveExpenses = (expenses: Expense[]): void => {
  localStorage.setItem(EXPENSES_KEY, JSON.stringify(expenses));
};

export const loadSuppliers = (): Supplier[] => {
  try {
    const data = localStorage.getItem(SUPPLIERS_KEY);
    return data ? JSON.parse(data) : defaultSuppliers;
  } catch {
    return defaultSuppliers;
  }
};

export const saveSuppliers = (suppliers: Supplier[]): void => {
  localStorage.setItem(SUPPLIERS_KEY, JSON.stringify(suppliers));
};

export const loadStockMovements = (): StockMovement[] => {
  try {
    const data = localStorage.getItem(STOCK_MOVEMENTS_KEY);
    return data ? JSON.parse(data) : defaultStockMovements;
  } catch {
    return defaultStockMovements;
  }
};

export const saveStockMovements = (movements: StockMovement[]): void => {
  localStorage.setItem(STOCK_MOVEMENTS_KEY, JSON.stringify(movements));
};

export const resetAllDataToDefault = (): void => {
  localStorage.setItem(SETTINGS_KEY, JSON.stringify(defaultSettings));
  localStorage.setItem(PRODUCTS_KEY, JSON.stringify(defaultProducts));
  localStorage.setItem(CUSTOMERS_KEY, JSON.stringify(defaultCustomers));
  localStorage.setItem(INVOICES_KEY, JSON.stringify(defaultInvoices));
  localStorage.setItem(PO_KEY, JSON.stringify(defaultPurchaseOrders));
  localStorage.setItem(EXPENSES_KEY, JSON.stringify(defaultExpenses));
  localStorage.setItem(SUPPLIERS_KEY, JSON.stringify(defaultSuppliers));
  localStorage.setItem(STOCK_MOVEMENTS_KEY, JSON.stringify(defaultStockMovements));
};

// Aliases for compatibility
export const getShopSettings = loadShopSettings;
export const getProducts = loadProducts;
export const getCustomers = loadCustomers;
export const getInvoices = loadInvoices;
export const getPurchaseOrders = loadPurchaseOrders;
export const getExpenses = loadExpenses;
export const getSuppliers = loadSuppliers;
export const getStockMovements = loadStockMovements;
export const resetToSampleData = resetAllDataToDefault;
